### ISSUE TITLE
XML file still refers to 1.0.7

### ISSUE THREAD

**Issue by mkis84** [wallee-payment/jtl-5#1]
The new version 1.0.8 still refers to 1.0.7 in info.xml. It is not possible to update ifrom 1.0.7 to 1.0.8 in the shop backend.

**Comment by thibault-mambour** [comment]
Hi @mkis84 , we made a small mistake that the version tag was incorrect and should be fixed with the new release. Sorry for the inconvenience.

**Comment by mkis84** [comment]
No problem. Thanks for fixing it :)
